This is makeindex, version 2.15 [TeX Live 2020/W32TeX] (kpathsea + Thai support).
Scanning style file ./thesis_draft_thd.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis_draft_thd.acn....done (65 entries accepted, 0 rejected).
Sorting entries....done (415 comparisons).
Generating output file thesis_draft_thd.acr....done (47 lines written, 0 warnings).
Output written in thesis_draft_thd.acr.
Transcript written in thesis_draft_thd.alg.
